Improve ghe support
motemen/chrome-GitHub-Issue-Badges pull request #10
Opened 2017-05-19 02:40 UTC by yashigani

# Problem
GitHub Issue Badges for GHE support only one ghe ( #7 ) .

# Change
- Improve options page
  - Add UI to manage multiple GHE

2017-05-26 09:27 UTC, grassedge requested changes
Thanks for your contribution!
I commented on your code, please check it.

2017-05-26 09:27 UTC, grassedge commented on src/ts/app.tsx
> +    return mode == 'github';
`===` is better than `==` .

2017-05-26 09:27 UTC, grassedge commented on src/ts/app.tsx
> +})(localStorage.getItem('mode'));
I suppose that following code is enough.

```javascript
const github = (localStorage.getItem('mode') === 'github');
```

2017-05-26 09:27 UTC, grassedge commented on src/ts/app.tsx
> +  addItem() {
```javascript
class App {
  constructor() {
    this.addItem = this.addItem.bind(this);
    ...
  }
  addItem() { ... }
}
```

Above code can be converted to 

```javascript
class App {
  addItem = () => { ... }
}
```

typescript compiler outputs following code.

```javascript
function App() {
  this.addItem = () => { ... };
  ...
}
```

so both above code behave the same action.
removeItem/updateStatus/saveConfigs/onConfigChanged also.

2017-05-26 09:27 UTC, grassedge commented on src/ts/app.tsx
> +    const newGithub = this.state.newGithub;
[may] if `newGithub` is false, you can return immediatly.

2017-05-26 09:27 UTC, grassedge commented on src/ts/app.tsx
> +      let config: Config = { origin: newGithub, apiRoot: apiRoot, token: '', status: TokenStatus.unchecked }
`config` is imutable, so you can use `const` instead of `let`.

2017-05-26 09:27 UTC, hatz48 commented on src/ts/app.tsx
> +  updateStatus(i: number) {
I think `updateTokenStatus` is better, because `status` and `this.state` is confusingly similar.

2017-05-26 09:27 UTC, hatz48 commented on src/ts/app.tsx
> +    if (config === undefined && config.apiRoot === undefined) {
not `&&` but `||` ?

2017-05-26 09:27 UTC, hatz48 commented on src/ts/app.tsx
> +    xhr.onload = function(e) {
Displaying `xhr.responseText` is helpful for users to understand what to do next.

2017-05-29 23:24 UTC, yashigani commented
@hatz48 Thanks your review. I tried to change the code.

2017-05-30 05:07 UTC, hatz48 commented
Looks good to me !

2017-05-30 05:25 UTC, grassedge approved these changes

2017-05-30 05:27 UTC, merged

2017-05-30 05:27 UTC, hatz48 commented
thx!

2017-05-30 05:57 UTC, motemen commented
Thanks, just uploaded to Chrome store as v2.5.0.